
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import UserContextProvider from "./userContext";

import axios from "axios";
import AccountPage from "./pages/accountPage/page";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
 

  return (
   <UserContextProvider>
     <html lang="en">
     
      <body className={inter.className}>
      <NavBar/>
       
        {children}
      

      </body>
    </html>
   </UserContextProvider>
  );
}
